In [6]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

# Generate some example data

In [7]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
df = pd.DataFrame(data, index=['a','b','c'], columns=['A','B','C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

# Create a MinMaxScaler instance 

In [14]:
scaler = MinMaxScaler()

In [16]:
data_transform = scaler.fit_transform(df)

In [18]:
data_transform

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

# Using fit and transfrom seperately

In [19]:
scaler.fit(data)

MinMaxScaler()

In [20]:
data_transformed_separate = scaler.transform(data)

In [21]:
data_transformed_separate

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])